version: 0.2

phases:
  pre_build:
    commands:
      - echo "Login to ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 585008076834.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t black_list_app .
      - echo "Tagging the Docker image..."
      - docker tag black_list_app:latest 585008076834.dkr.ecr.us-east-1.amazonaws.com/black_list_app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 585008076834.dkr.ecr.us-east-1.amazonaws.com/black_list_app:latest
      - printf '[{"name":"Container-app-blacklist","imageUri":"585008076834.dkr.ecr.us-east-1.amazonaws.com/black_list_app:latest"}]' > imagedefinitions-cd.json
      - printf '{"ImageURI":"585008076834.dkr.ecr.us-east-1.amazonaws.com/black_list_app:latest"}' > imageDetail-cd.json
      - cat imagedefinitions-cd.json
artifacts:
  files:
    - '**/*'
    - imagedefinitions-cd.json
    - imageDetail-cd.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec-cd.json
        - taskdef-cd.json
    ImageArtifact:
      files:
        - imageDetail-cd.json