version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install pipenv
      - pipenv install
  pre_build:
    commands:
      - echo "Running pre-build commands..."
      - pipenv install --dev
  build:
    commands:
      - echo "Execute unit test..."
      - pipenv run pytest --cov=. -v -s --cov-fail-under=70 --cov-report=html --cov-report=xml --junitxml=report.xml
  post_build:
    commands:
      - echo "Packaging the application and coverage report..."
      - zip -r blacklist-app-${CODEBUILD_BUILD_NUMBER}.zip . -x "*.git*" "*.pytest_cache*" "*.coverage*" "*__pycache__*" "*.env*" "*.venv*" "*.idea*" "*.vs*" "*htmlcov*"
      - zip -r coverage-report-${CODEBUILD_BUILD_NUMBER}.zip htmlcov/
artifacts:
  files:
    - '**/*-${CODEBUILD_BUILD_NUMBER}.zip'
    - report.xml
    - coverage.xml
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip/**/*'
