version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install pipenv
      - echo Installing dependencies...
      - pipenv install
  pre_build:
    commands:
      - echo Running pre-build commands...
      - pipenv install --dev
  post_build:
    commands:
      - echo Running post-build commands...
      - pipenv run pytest --cov=. -v -s --cov-fail-under=70

artifacts:
  files:
    - '**/*'
  name: blacklist-app
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip/**/*'
